apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: production-grade
  namespace: production-grade
spec:
  version: 7.9.3
  count: 1
  elasticsearchRef:
    name: "production-grade"
    namespace: production-grade
  # this allows ECK to configure automatically the Kibana endpoint as described in https://www.elastic.co/guide/en/apm/server/current/setup-kibana-endpoint.html
  kibanaRef:
    name: "production-grade"
    namespace: production-grade
  config:
    apm-server.jaeger.grpc.enabled: true
    apm-server.jaeger.grpc.host: "0.0.0.0:14250"
    # https://www.elastic.co/guide/en/apm/server/7.9/monitoring-metricbeat-collection.html
    http.enabled: true
    http.port: 5066
    http.host: 0.0.0.0
    monitoring.enabled: false
  podTemplate:
    metadata:
      labels:
        stack-monitoring.elastic.co/type: beat # to allow autodiscover by metricbeat
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
      - name: apm-server
        ports:
        - containerPort: 5066
          name: monitoring
          protocol: TCP
  http:
    service:
      spec:
        type: Nodeport
        ports:
          - name: http
            port: 8200
            targetPort: 8200
          - name: grpc
            port: 14250
            targetPort: 14250

#  # inject secure settings into APM Server keystore from k8s secrets references
#   secureSettings:
#   - secretName: ref-to-secret
#   - secretName: another-ref-to-secret
#     # expose only a subset of the secret keys (optional)
#     entries:
#     - key: value1
#       path: newkey # project a key to a specific path (optional)
