apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: production-grade
  namespace: production-grade
spec:
  version: 7.9.2
  nodeSets:
  # Dedicated master nodes
  - name: master
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      # Check https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
      # node.store.allow_mmap: false
    podTemplate:
        spec:
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
          - name: elasticsearch
            env:
            - name: PRE_STOP_MAX_WAIT_SECONDS
              value: "10"
            - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
              value: "5"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
            resources:
              limits:
                memory: 4Gi
                cpu: 2

  # Dedicated data nodes
  - name: data
    count: 6
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      # Check https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
      # node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: sc
    podTemplate:
        spec:
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
          - name: elasticsearch
            env:
            - name: PRE_STOP_MAX_WAIT_SECONDS
              value: "10"
            - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
              value: "5"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
            resources:
              limits:
                memory: 4Gi
                cpu: 3
  # Dedicated ingest nodes
  - name: ingest
    count: 3
    config:
      node.master: false
      node.data: false
      node.ingest: true
      node.ml: false
      # Check https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
      # node.store.allow_mmap: false
    podTemplate:
        spec:
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
          - name: elasticsearch
            env:
            - name: PRE_STOP_MAX_WAIT_SECONDS
              value: "10"
            - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
              value: "5"

  # Dedicated coordinator nodes
  - name: coordinator
    count: 3
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: false
      # Check https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
      # node.store.allow_mmap: false
    podTemplate:
        spec:
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
          - name: elasticsearch
            env:
            - name: PRE_STOP_MAX_WAIT_SECONDS
              value: "10"
            - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
              value: "5"

  # Dedicated machine learning nodes
  - name: ml
    count: 3
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: true
      # Check https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
      # node.store.allow_mmap: false
    podTemplate:
        spec:
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
          - name: elasticsearch
            env:
            - name: PRE_STOP_MAX_WAIT_SECONDS
              value: "10"
            - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
              value: "5"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
            resources:
              limits:
                memory: 4Gi
                cpu: 4
