apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: production-grade
  namespace: production-grade
spec:
  version: 7.9.3
  count: 3
  elasticsearchRef:
    name: production-grade
    namespace: production-grade
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 2

  http:
    service:
      spec:
        type: NodePort
