apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: production-grade
  namespace: production-grade
spec:
  version: 7.9.2
  count: 1
  elasticsearchRef:
    name: production-grade
    namespace: production-grade
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1

  #http:
  #  service:
  #    spec:
  #      type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
